### ISSUE TITLE
Compatibility with Logseq tabs plugin

### ISSUE THREAD

**Issue by aadilayub** [wirtzdan/logseq-paper-theme#13]
![image](https://user-images.githubusercontent.com/31581044/167262941-98ddfc19-75c1-42ec-8e6b-3c5be35f6aa6.png)

Reporting this issue because this is a very popular plugin that adds useful functionality to Logseq. It looks alright on every theme, except 
this one where it clashes with the card design.

Ideally, the tabs would be above the card/page like this:

![image](https://user-images.githubusercontent.com/31581044/167263262-68808b58-b9e7-4e7a-af9a-f8e64a63afca.png)

I made them appear like this with a `position: absolute` hack, but perhaps there is a better solution that follows the code conventions of this theme.

**Comment by aadilayub** [comment]
I added the following lines to `custom.css` to make the tabs plugin work fit with the theme:

```css
#main-content-container { margin-top: 65px !important; }
#logseq-tabs_lsp_main { top: 49px !important; }
```
Result:

![image](https://user-images.githubusercontent.com/31581044/168425946-b7e53703-d552-41ed-ba4f-cb93e897db96.png)
